
import { Lead, LeadSource, PipelineStage, User } from './pages/types';

const MOCK_COMPANY_ID = 1;

export const MOCK_USERS: User[] = [
  {
    id: 1,
    authUserId: 'mock-user-1',
    name: 'Ana Souza',
    email: 'ana@empresa.com',
    role: 'vendedor',
    companyId: MOCK_COMPANY_ID,
    isActive: true
  },
  {
    id: 2,
    authUserId: 'mock-user-2',
    name: 'João Lima',
    email: 'joao@empresa.com',
    role: 'vendedor',
    companyId: MOCK_COMPANY_ID,
    isActive: true
  },
  {
    id: 3,
    authUserId: 'mock-user-3',
    name: 'Carla Gestora',
    email: 'carla@empresa.com',
    role: 'admin',
    companyId: MOCK_COMPANY_ID,
    isActive: true
  },
];

const subDays = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Maria Fernandes',
    company: 'SolarTech RJ',
    email: 'maria@solartech.com',
    phone: '5521999990001',
    source: LeadSource.FORMULARIO,
    value: 15000,
    createdAt: subDays(2),
    stage: PipelineStage.NOVO,
    ownerId: 1,
    notes: 'Interessada em automação do funil de vendas.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '2',
    name: 'Paulo Ribeiro',
    company: 'Energia Pura',
    email: 'paulo@energiapura.com',
    phone: '5521988880002',
    source: LeadSource.WHATSAPP,
    value: 22000,
    createdAt: subDays(0), // Hoje
    stage: PipelineStage.EM_ATENDIMENTO,
    ownerId: 2,
    notes: 'Já recebeu proposta inicial.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '3',
    name: 'Loja Horizonte',
    company: 'Loja Horizonte',
    email: 'contato@horizonte.com',
    phone: '5521977770003',
    source: LeadSource.REDES_SOCIAIS,
    value: 8000,
    createdAt: subDays(7),
    stage: PipelineStage.VENDA_FEITA,
    ownerId: 1,
    notes: 'Negócio fechado, implementar CRM em 30 dias.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '4',
    name: 'Gustavo Lima',
    company: 'GL Serviços',
    email: 'gustavo@glservicos.com',
    phone: '5521966660004',
    source: LeadSource.INDICACAO,
    value: 12000,
    createdAt: subDays(10),
    stage: PipelineStage.FINALIZADO,
    ownerId: 2,
    notes: 'Cliente optou por concorrente.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '5',
    name: 'Tech Solutions',
    company: 'Tech Solutions',
    email: 'contato@techsolutions.com',
    phone: '5511999990005',
    source: LeadSource.OUTROS,
    value: 45000,
    createdAt: subDays(1),
    stage: PipelineStage.REUNIAO_AGENDADA,
    ownerId: 3,
    notes: 'Grande potencial. Reunião agendada.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '6',
    name: 'Roberto Alves',
    company: 'Alves Consultoria',
    email: 'roberto@alves.com',
    phone: '5511988880006',
    source: LeadSource.FORMULARIO,
    value: 5000,
    createdAt: subDays(15),
    stage: PipelineStage.FOLLOW_UP,
    ownerId: 1,
    notes: 'Lead frio, fazer follow-up em 2 dias.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '7',
    name: 'Clara Nunes',
    company: 'CN Design',
    email: 'clara@cndesign.com',
    phone: '5531999990007',
    source: LeadSource.REDES_SOCIAIS,
    value: 9500,
    createdAt: subDays(3),
    stage: PipelineStage.VENDA_FEITA,
    ownerId: 2,
    notes: 'Pagamento confirmado.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '8',
    name: 'Marcos Viana',
    company: 'Viana Imports',
    email: 'marcos@viana.com',
    phone: '5541999990008',
    source: LeadSource.WHATSAPP,
    value: 32000,
    createdAt: subDays(5),
    stage: PipelineStage.REUNIAO_AGENDADA,
    ownerId: 1,
    notes: 'Aguardando feedback da diretoria.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '9',
    name: 'Juliana Paes',
    company: 'JP Eventos',
    email: 'juliana@jp.com',
    phone: '5521999990009',
    source: LeadSource.INDICACAO,
    value: 18000,
    createdAt: subDays(20),
    stage: PipelineStage.FOLLOW_UP,
    ownerId: 2,
    notes: 'Verificar interesse novamente.',
    companyId: MOCK_COMPANY_ID,
  },
  {
    id: '10',
    name: 'Pedro Santos',
    company: 'Santos Logística',
    email: 'pedro@santos.com',
    phone: '5511977770010',
    source: LeadSource.FORMULARIO,
    value: 60000,
    createdAt: subDays(4),
    stage: PipelineStage.NOVO,
    ownerId: 3,
    notes: 'Lead Enterprise.',
    companyId: MOCK_COMPANY_ID,
  },
];
